# Generated by Django 4.2.3 on 2023-12-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_otherleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='exp_certificate_status',
            field=models.CharField(default='null', max_length=15, null=True),
        ),
    ]
